import { inter } from './fonts'
import './globals.css'

export const metadata = {
  title: {
    defaults: 'Multisite Image Search',
    template: '%s | Multisite Image Search',
  },
  robots: {
    index: true,
    follow: true,
    googlebot: {
      index: true,
      follow: true,
      'max-snippet': -1,
      'max-image-preview': 'large',
      'max-video-preview': '-1',
    }
  },
  description: 'Generated by create next app',
  canonical: 'https://search.photos',
  verification: {
    google: '',
    bing: '',
    yandex: '',
  },
  og: {
    title: '',
    description: '',
    type: 'website',
    url: '',
    image: '',
    site_name: '',
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    site: '@site',
    creator: '@creator',
  },
  facebook: {
    app_id: '',
  },
  theme_color: '#ffffff',
  background_color: '#ffffff',
  favicon: '/favicon.ico',
  apple: {
    icon: '/apple-touch-icon.png',
    icon_180: '/apple-touch-icon.png',
    icon_167: '/apple-touch-icon.png',
    icon_152: '/apple-touch-icon.png',
    icon_120: '/apple-touch-icon.png',
    icon_76: '/apple-touch-icon.png',
    icon_60: '/apple-touch-icon.png',
    icon_57: '/apple-touch-icon.png',
  },
  ms: {
    tile: '/mstile-144x144.png',
    tile_color: '#ffffff',
  },
  manifest: '/manifest.json',
  safari: {
    pinned: '/safari-pinned-tab.svg',
  },
  mask_icon: '/safari-pinned-tab.svg',
  msapplication: {
    tooltip: 'Tooltip',
    start_url: '/',
    tile_image: '/mstile-144x144.png',
    tile_color: '#ffffff',
  },
  yandex: {
    verification: '',
  },
  android: {
    icon: '/android-chrome-192x192.png',
    icon_192: '/android-chrome-192x192.png',
    icon_512: '/android-chrome-512x512.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  )
}
